ADDED THE CODE FOR FACE RETRIEVAL
akshitagupta15june/Face-X pull request #585
Opened 2021-05-15 10:01 UTC by ainy-123

# Related Issues or bug
  Face Retrieval from a given image

Fixes: #447 

# Proposed Changes
added the files in the Face_Retrieval folder under awesome-face-operations folder.

# Additional Info
  Kindly Review my PR and merge.
  
# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **![face](https://user-images.githubusercontent.com/61025442/118356308-3b51c780-b592-11eb-939d-00074f4ddd48.jpg)** | **![final_face_retrieved](https://user-images.githubusercontent.com/61025442/118356339-7227dd80-b592-11eb-8d9e-c81d3d72ef73.png) **|

2021-05-15 11:41 UTC, akshitagupta15june requested changes
Can u add a proper output screenshot in readme?md

2021-05-15 11:46 UTC, ainy-123 commented
> Can u add a proper output screenshot in readme?md

Ya sure,you mean the link for input and output image ,which I have attached here in PR should be added in README.md ,right?

2021-05-15 12:24 UTC, ainy-123 commented
> Can u add a proper output screenshot in readme?md

I have done the changes ,you have requested for.
Kindly check it.

2021-05-16 10:31 UTC, akshitagupta15june approved these changes

2021-05-16 10:31 UTC, merged